# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import square_pb2 as square__pb2


class SquareStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SquareRoot = channel.unary_unary(
        '/Square/SquareRoot',
        request_serializer=square__pb2.Number.SerializeToString,
        response_deserializer=square__pb2.Number.FromString,
        )


class SquareServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SquareRoot(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SquareServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SquareRoot': grpc.unary_unary_rpc_method_handler(
          servicer.SquareRoot,
          request_deserializer=square__pb2.Number.FromString,
          response_serializer=square__pb2.Number.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Square', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
